apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 3
spec:
  selector:
    matchLabels:
      run: {{ .Values.appName }}
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Values.appName }}
        app: {{ .Values.appName }}
        imageTag: "v1.0.1"
    spec:
      serviceAccountName: "{{ .Values.appName }}-service-role"
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.resources.containerInfo.containerPort }}
    {{ if hasKey .Values "tolerations" }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{ end }}
      {{ if hasKey .Values "nodeSelector" }}
      nodeSelector:
      {{ with .nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ end }}